version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: