version: '3.8'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    depends_on:
      - db
    environment:
      - SECRET_KEY=3282afdb4c1473d9f7b5b984ddf00098f33cba2b9f05c0ea299f11b9984bb6e8
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300
      - DB_URL=postgresql://postgres:postgres@db/db
      - GEMINI_KEY=AIzaSyA5IP7hnfWl3HEbQpCHXCmEqrdWHiTNF18
volumes:
  postgres_data: