"""modify many 2 many relationship

Revision ID: 080f0a07adf5
Revises: dfb77b0d4527
Create Date: 2024-05-09 20:14:29.231102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080f0a07adf5'
down_revision: Union[str, None] = 'dfb77b0d4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_payment_id', table_name='transaction_payment')
    op.drop_table('transaction_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_payment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='transaction_payment_payment_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_payment_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'transaction_id', 'payment_id', name='transaction_payment_pkey')
    )
    op.create_index('ix_transaction_payment_id', 'transaction_payment', ['id'], unique=False)
    # ### end Alembic commands ###
