"""Add Label and change default function

Revision ID: 4673447d815c
Revises: f6b8a65803b7
Create Date: 2024-05-03 18:28:54.753750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4673447d815c'
down_revision: Union[str, None] = 'f6b8a65803b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('desc', sa.String(), nullable=True))
    op.alter_column('transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('transaction', 'desc')
    # ### end Alembic commands ###
