"""Change Description Name

Revision ID: 92d40e24a5f4
Revises: 4673447d815c
Create Date: 2024-05-03 18:31:37.208529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d40e24a5f4'
down_revision: Union[str, None] = '4673447d815c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('transaction', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'description')
    # ### end Alembic commands ###
