"""Test

Revision ID: a9f649580727
Revises: bd87fada29b0
Create Date: 2024-05-02 20:42:28.193226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f649580727'
down_revision: Union[str, None] = 'bd87fada29b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
