"""update contraint in friends table

Revision ID: dacb010c50ca
Revises: 2e42bd24aa12
Create Date: 2024-05-02 21:06:46.716141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacb010c50ca'
down_revision: Union[str, None] = '2e42bd24aa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'friend', 'users', ['friend_id'], ['id'])
    op.create_foreign_key(None, 'friend', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend', type_='foreignkey')
    op.drop_constraint(None, 'friend', type_='foreignkey')
    # ### end Alembic commands ###
