"""Add on delete

Revision ID: f1ca7353aae2
Revises: 0601f5a66d0f
Create Date: 2024-05-09 20:32:21.444986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ca7353aae2'
down_revision: Union[str, None] = '0601f5a66d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_transaction_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transaction_payment_transaction_id_fkey', 'transaction_payment', type_='foreignkey')
    op.drop_constraint('transaction_payment_payment_id_fkey', 'transaction_payment', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_payment', 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transaction_payment', 'payment', ['payment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_payment', type_='foreignkey')
    op.drop_constraint(None, 'transaction_payment', type_='foreignkey')
    op.create_foreign_key('transaction_payment_payment_id_fkey', 'transaction_payment', 'payment', ['payment_id'], ['id'])
    op.create_foreign_key('transaction_payment_transaction_id_fkey', 'transaction_payment', 'transaction', ['transaction_id'], ['id'])
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_transaction_id_fkey', 'payment', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
